blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.PostList.as_view(), name="home"),
    path("blog/", views.create_post, name="create_post"),
    path("blog/<slug:slug>/", views.PostDetail.as_view(), name="post_detail"),
    path(
        "blog/<int:blog_post_id>/",
        views.PostDetail.as_view(),
        name="blog_detail"
        ),
    path("like/<slug:slug>", views.PostLike.as_view(), name="post_like"),
    path(
        "blog/delete/<int:blog_post_id>",
        views.delete_post,
        name="delete_post"
        ),
    path("blog/<slug:slug>/update/", views.update_post, name="update_post"),
    path("newsletter/subscribe", views.subscribe, name="subscribe"),
    path("newsletter/unsubscribe", views.unsubscribe, name="unsubscribe"),
    path("newsletter/update", views.editemail, name="editemail"),
    path("newsletter/send", views.new_email, name="new_email"),
]

devstories/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("accounts/", include("allauth.urls")),
    path("summernote/", include("django_summernote.urls")),
]

blog/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    """Model class for post"""

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField("image", default="placeholder")
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="blog_likes", blank=True)

    class Meta:
        ordering = ["-created_on"]

    def _str_(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

    def get_absolute_url(self):
        """Returns comment with primary key"""
        return reverse("post_detail", kwargs={"pk": self.pk})


class Newsletter(models.Model):
    email = models.EmailField(max_length=254, null=False, blank=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="A blog site for Developers">
    <meta name="keywords" content="Blog">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
        </script>
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <title>Devstories | Home</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <div class="col">
                <a class="navbar-brand text-white" href="{% url 'home' %}"><span class="brand text-white">Dev<span
                            class="red-o text-white">stor</span>ies<span class="thin"> | Dev Blogs |
                        </span></span></span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link active text-white" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active text-white" href="{% url 'create_post' %}">New Post</a>
                    </li>
                    <li class="nav-item">
                        <form method="post" action="{% url 'account_logout' %}">
                            {% csrf_token %}
                            {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                            {% endif %}
                            <button class="nav-link active text-dark" type="submit">logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active text-white" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active text-white" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<body>
    <main class="flex-shrink-0 main-bg">
        <!-- Background image -->
        <div class="text-center bg-image"
            style="background-image: url({% static 'media/blog-hero.jpg' %}); height: 400px;">
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.6); height: 400px">
                <div class="d-flex justify-content-center align-items-center h-100">
                    <div class="text-white">
                        <h1 class="mb-3">Devstories</h1>
                        <h4 class="mb-3">A Blog site for Developers and Friends</h4>
                    </div>
                </div>
            </div>
        </div>
        <!-- Background image -->
        <div class="container">
            <div class="row">
                <div class="col md-8 offset-md-2">
                    {% for message in messages %}
                    <div class="alert {{ message.tag }} alert-dismissible fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="blog-content">
            {% block content %}
            {% endblock content %}
        </div>
    </main>

    <footer class="card text-center bg-dark mt-14">
        <div class="card-body text-white">
            <h5 class="card-title">Devstories</h5>
            <p class="card-text">Personal blog site for my projects.</p>
        </div>
        <div class="card-header text-white">
            <p>&copy; Devstories | 2023</p>
        </div>
    </footer>

</body>

</html>

templates/index.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    {% for post in post_list %}
    <div class="col-12 col-md-6">
      <div class="card mb-4">
        <div class="card-body">
          <a href="{% url 'post_detail' post.slug %}" class="post-link">
            <h2 class="card-title text-center">{{ post.title }}</h2>
            <div class="image-container">
              {% if "placeholder" in post.featured_image.url %}
              <img
                class="card-img-top"
                src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg"
              />
              {% else %}
              <img class="card-img-top" src=" {{ post.featured_image.url }}" />
              {% endif %}
              <div class="image-flash">
                <p class="author">Author: {{ post.author }}</p>
              </div>
            </div>
            <p class="card-text text-center">{{ post.excerpt }}</p>
          </a>
          <hr />
          <p class="card-text text-muted h6">
            {{ post.created_on}} <i class="far fa-heart"></i> {{ post.number_of_likes }}
          </p>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:4 %}
  </div>
  <div class="col">{% endif %} {% endfor %}</div>
  {% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li>
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link"
          >&laquo; PREV
        </a>
      </li>
      {% endif %} {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">
          NEXT &raquo;</a
        >
      </li>

      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
<div>
  <form
    class="mt-3 container w-25"
    action="{% url 'subscribe' %}"
    method="POST"
    id="profile-update-form"
  >
    <p class="text-center">Subscribe To Our Newsletter</p>
    <p class="text-center">To get notified when a new blog is posted</p>
    {% csrf_token %}
    <input
      type="email"
      name="email"
      maxlength="254"
      class="border-black rounded-0 emailinput form-control"
      required=""
      id="id_email"
      placeholder="Enter your Email to subscribe"
    />
    <div class="d-flex justify-content-center py-3">
      <button class="btn rounded-0 text-uppercase float-right">
        Subscribe to Newsletter
      </button>
    </div>
  </form>
  <form
    class="container w-25"
    action="{% url 'unsubscribe' %}"
    method="POST"
    id="profile-update-form"
  >
    {% csrf_token %}
    <!-- <input type="email" name="email" maxlength="254" class="border-black rounded-0 emailinput form-control" required="" id="id_email" 
        placeholder="Enter your Email to unsubscribe"> -->
    <input
      type="email"
      name="email"
      maxlength="254"
      class="border-black rounded-0 emailinput form-control"
      required
      id="id_email"
    />
    <div class="d-flex justify-content-center py-3">
      <button class="btn rounded-0 text-uppercase float-right">
        UnSub from our Newsletter
      </button>
    </div>
  </form>
</div>

{%endblock%}

templates/new_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}
  Create a post
{% endblock head_title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-8 offset-2">
        <h2 class="text-center my-5">Create a new post</h2>
        <form class=""
              method="post"
              action="{% url 'create_post' %}"
              enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            {{ form.title.label_tag }}
            <div id="div_id_title" class="form-group">
              <div>
                <input type="text"
                       name="title"
                       maxlength="200"
                       class="textinput textInput form-control"
                       required=""
                       id="id_title">
              </div>
            </div>
          </div>
          <div class="form-group">
            {{ form.slug.label_tag }}
            <div id="div_id_slug" class="form-group">
              <div>
                <input type="text"
                       name="slug"
                       maxlength="200"
                       class="textinput textInput form-control"
                       required=""
                       id="id_slug">
              </div>
              {% if form.slug.errors %}<div class="invalid-feedback">{{ form.slug.errors }}</div>{% endif %}
            </div>
          </div>
          <div class="form-group">
            {{ form.content.label_tag }}
            <div id="div_id_content" class="form-group">
              <div>
                <textarea name="content"
                          cols="40"
                          rows="10"
                          class="textarea form-control"
                          required=""
                          id="id_content"></textarea>
              </div>
              {% if form.content.errors %}<div class="invalid-feedback">{{ form.content.errors }}</div>{% endif %}
            </div>
          </div>
          <div class="form-group">
            <div id="div_id_featured_image" class="form-group">
              {{ form.featured_image.label_tag }}
              <div>
                <input type="file"
                       name="featured_image"
                       class="clearablefileinput form-control-file"
                       id="id_featured_image">
              </div>
              {% if form.featured_image.errors %}<div class="invalid-feedback">{{ form.featured_image.errors }}</div>{% endif %}
            </div>
            <div id="div_id_excerpt" class="form-group">
              {{ form.excerpt.label_tag }}
              <div>
                <textarea name="excerpt"
                          cols="40"
                          rows="10"
                          class="textarea form-control"
                          id="id_excerpt"></textarea>
              </div>
              <div class="my-5 text-center">
                <button class="btn btn-primary mb-2" type="submit">Create New Post</button>
              </div>
            </div>
          </div>
        </form>
        <form class="container w-25"
              action="{% url 'editemail' %}"
              method="POST"
              id="profile-update-form">
          {% csrf_token %}
          <input type="email"
                 name="email"
                 maxlength="254"
                 placeholder="update your email here"
                 class="border-black rounded-0 emailinput form-control"
                 required
                 id="id_email">
          <div class="d-flex justify-content-center py-3">
            <button class="btn rounded-0 text-uppercase float-right">Update or Change your Email Newsletter</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
  {% load crispy_forms_tags %}
  <div class="masthead">
    <div class="container">
      <div class="row g-0">
        <div class="col-md-6 masthead-text">
          <!-- Post title goes in these h1 tags -->
          <h1 class="post-title">{{ post.title }} - {{ post.author.id }}</h1>
          <!-- Post author goes before the | the post's created date goes after -->
          <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
        </div>
        <div class="d-none d-md-block col-md-6 masthead-image">
          <!-- The featured image URL goes in the src attribute -->
          {% if "placeholder" in post.featured_image.url %}
            <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg"
                 width="100%">
          {% else %}
            <img src=" {{ post.featured_image.url }}" width="100%">
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col card mb-4  mt-3 left  top">
        <div class="card-body">
          <!-- The post content goes inside the card-text. -->
          <!-- Use the | safe filter inside the template tags -->
          <p class="card-text ">{{ post.content | safe }}</p>
          <div class="row">
            <div class="col-1">
              <!-- The number of likes goes before the closing strong tag -->
              <strong>
                {% if user.is_authenticated %}
                  <form class="d-inline"
                        action="{% url 'post_like' post.slug %}"
                        method="POST">
                    {% csrf_token %}
                    {% if liked %}
                      <button type="submit"
                              name="blogpost_id"
                              value="{{ post.slug }}"
                              class="btn-like">
                        <i class="fas fa-heart"></i>
                      </button>
                    {% else %}
                      <button type="submit"
                              name="blogpost_id"
                              value="{{ post.slug }}"
                              class="btn-like">
                        <i class="far fa-heart"></i>
                      </button>
                    {% endif %}
                  </form>
                {% else %}
                  <span class="text-secondary"><i class="far fa-heart"></i></span>
                {% endif %}
                <span class="text-secondary">{{ post.number_of_likes }}</span>
              </strong>
              {% if user.is_authenticated %}
                {% if user.id == post.author.id %}
                  <form method="POST" action="{% url 'delete_post' blog_post_id=post.pk %}">
                    {% csrf_token %}
                    <button type="delete" class="btn btn-danger btn-lg">Delete</button>
                  </form>
                  <form class="mt-4"
                        method="POST"
                        action="{% url 'update_post' slug=post.slug %}">
                    {% csrf_token %}
                    <button type="update" class="btn btn-secondary btn-lg">Update</button>
                  </form>
                {% endif %}
              {% endif %}
            </div>
            <div class="col-1">
              {% with comments.count as total_comments %}
              <strong class="text-secondary"><i class="far fa-comments"></i>
              <!-- Our total_comments variable goes before the closing strong tag -->
            {{ total_comments }}</strong>
          {% endwith %}
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <hr />
  </div>
</div>
<div class="row">
  <div class="col-md-8 card mb-4  mt-3 ">
    <h3>Comments:</h3>
    <div class="card-body">
      <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
      {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              <!-- The comment's created date goes here -->
              {{ comment.created_on }}
            </span> wrote:
          </p>
          <!-- The body of the comment goes before the | -->
          {{ comment.body | linebreaks }}
        </div>
        <!-- Our for loop ends here -->
      {% endfor %}
    </div>
  </div>
  <div class="col-md-4 card mb-4  mt-3 ">
    <div class="card-body">
      <!-- For later -->
      {% if commented %}
        <div class="alert alert-success" role="alert">Your comment is awaiting approval</div>
      {% else %}
        {% if user.is_authenticated %}
          <h3>Leave a comment:</h3>
          <p>Posting as: {{ user.username }}</p>
          <form method="post" style="margin-top: 1.3em;">
            {{ comment_form | crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-signup btn-lg">Submit</button>
          </form>
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>
</div>
{% endblock content %}

templates/update_post.html
{% extends "base.html" %}
{% block head_title %}
Update a post
{% endblock head_title %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class="text-center my-5">Updating {{ blog_post.title }}</h2>
      <form class="" method="post" action="{% url 'update_post' slug=blog_post.slug %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ form.title.label_tag }}
          <div id="div_id_title" class="form-group">
            <div>
              <input type="text" name="title" maxlength="200"class="textinput textInput form-control" required="" value="{{ blog_post.title }}" id="id_title">
            </div>
          </div>
        </div>
        <div class="form-group">
          {{ form.slug.label_tag }}
          <div id="div_id_slug" class="form-group">
            <div>
              <input type="text" name="slug" maxlength="200" class="textinput textInput form-control" required="" value="{{ blog_post.slug }}" id="id_slug">
            </div>
            {% if form.slug.errors %}
              <div class="invalid-feedback">{{ form.slug.errors }}</div>
            {% endif %}
          </div>
        </div>
        <div class="form-group">
          {{ form.content.label_tag }}
          <div id="div_id_content" class="form-group">
            <div>
              <textarea name="content" cols="40" rows="10" class="textarea form-control" required="" value="{{ blog_post.content }}" id="id_content"></textarea>
            </div>
            {% if form.content.errors %}
              <div class="invalid-feedback">{{ form.content.errors }}</div>
            {% endif %}
          </div>
        </div>
        <div class="form-group">
          <div id="div_id_featured_image" class="form-group">
            {{ form.featured_image.label_tag }}
            <div>
              <input type="file" name="featured_image" class="clearablefileinput form-control-file" value="{{ blog_post.featured_image }}" id="id_featured_image">
            </div>
            {% if form.featured_image.errors %}
              <div class="invalid-feedback">{{ form.featured_image.errors }}</div>
            {% endif %}
          </div>
        </div>
        <div id="div_id_excerpt" class="form-group">
          {{ form.excerpt.label_tag }}
          <div>
            <textarea name="excerpt" cols="40" rows="10" class="textarea form-control" id="id_excerpt" value="{{ blog_post.excerpt }}"></textarea>
          </div>
          <div class="my-5 text-center">
            <button class="btn btn-primary mb-2" type="submit">Update Post</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}